Convergencia
andreslcm/FRONT_SF pull request #1
Opened 2019-11-07 14:01 UTC by andreslcm

![image](https://user-images.githubusercontent.com/48369945/68395080-d2dc8b80-014d-11ea-8dba-85cda98470b4.png)

2019-11-07 16:41 UTC, didierrenardub requested changes
Muy grande el PR, esto deberían haberlo subido de a poco...

2019-11-07 16:41 UTC, didierrenardub commented on public/index.html
> +      height: 100vh;
Nada de estilos inline, por favor. Hay que meterlo en un .css.

2019-11-07 16:41 UTC, didierrenardub commented on src/App.vue
> +export default {};
Export vacío no tiene sentido; toda la sección `script` puede desaparecer.

2019-11-07 16:41 UTC, didierrenardub commented on src/App.vue
> +      v-if="this.$route.name === 'landing' || this.$route.name === 'registro' || this.$route.name === 'login'"
Qué sucede si se intenta ingresar a una página que no es ninguna de esas 3?

2019-11-07 16:41 UTC, didierrenardub commented on src/components/AgregarFactura.vue
> +          <p>{{getDatosUsuario.nombre}} {{getDatosUsuario.apellido}}</p>
No faltan los () en `getDatosUsuario` previo al acceso a la propiedad `apellido`? Idem para las ocurrencias debajo.

2019-11-07 16:41 UTC, didierrenardub commented on src/components/Clientes.vue
> +.contenedor-clientes {
No se deja espacio entre las definiciones de clases.

2019-11-07 16:41 UTC, didierrenardub commented on src/components/Clientes.vue
> +.iconos:hover {
No se deja espacio.

2019-11-07 16:41 UTC, didierrenardub commented on src/components/Clientes.vue
> +.contenedor-tabla {
Otra vez no se deja espacio, aplicar para todo ( y hacerlo consistente en todos los archivos).

2019-11-07 16:41 UTC, didierrenardub commented on src/components/Estadisticas.vue
> +</style>
Componente vacío, no debería existir.

2019-11-07 16:41 UTC, didierrenardub commented on src/components/LandingPage.vue
> +</style>
Componente vacío, no debería existir.

2019-11-07 16:41 UTC, didierrenardub commented on src/components/Logged.vue
> +    <Clientes class="pagina" v-if="getContador === 1" />
No debería llamarse como `getContador()`? O así funciona? Lo mismo para las ocurrencias debajo.

2019-11-07 16:41 UTC, didierrenardub commented on src/components/Logged.vue
> +import Usuario from "./Usuario";
Falta el `.vue`.

2019-11-07 16:41 UTC, didierrenardub commented on src/components/Usuario.vue
> +      this.usuario.nombre = this.getDatosUsuario.nombre;
Nuevamente, no debería ser `getDatosUsuario()`? Por ahí Vue lo resuelve solo... si esto no es un método sino una propiedad, entonces debería llamarse `datosUsuario` para evitar confusión.

2019-11-07 16:41 UTC, didierrenardub commented on src/store.js
> +        });
En este y todos los casos debajo, qué pasa si no hay respuesta del servidor?

2019-11-07 16:47 UTC, andreslcm commented on public/index.html
> +      height: 100vh;
Bueno. Los metí ahí porque esa es la plantilla que me tira el Vue al crear un componente; al principio tenía casi toda mi atención en entender la lógica. Sin embargo, ya viéndolo ahora, sí quedaría mejor sacarlos.

2019-11-07 16:48 UTC, andreslcm commented on src/App.vue
> +export default {};
Este compoenente se borró. Venía por defecto.

2019-11-07 16:49 UTC, andreslcm commented on src/App.vue
> +      v-if="this.$route.name === 'landing' || this.$route.name === 'registro' || this.$route.name === 'login'"
Esto es un condicional de estilo. Si se accede a una de esas rutas, se muestra el menú que se ve al inicio. Ya cuando el usuario entra, no se muestra ese menú.

2019-11-07 16:50 UTC, andreslcm commented on src/components/AgregarFactura.vue
> +          <p>{{getDatosUsuario.nombre}} {{getDatosUsuario.apellido}}</p>
No. Cuando se llama desde el template no se colocan los (), a menos que se vaya a pasar algún parámetro.

2019-11-07 16:51 UTC, andreslcm commented on src/components/Clientes.vue
> +.contenedor-clientes {
Entendido.

2019-11-07 16:51 UTC, andreslcm commented on src/components/LandingPage.vue
> +</style>
Sí, señor. Otra persona está trabajando en él. En las próximas horas debería subir el contenido.

2019-11-07 16:53 UTC, andreslcm commented on src/components/Logged.vue
> +    <Clientes class="pagina" v-if="getContador === 1" />
Cuando se llama desde el template, se colocan los () si se van a pasar parámetros.

2019-11-07 16:55 UTC, andreslcm commented on src/components/Logged.vue
> +import Usuario from "./Usuario";
Eso es correcto. Necesario desde el punto de vista de la consistencia, no desde la funcionalidad (funciona igual con o sin la extensión).

2019-11-07 17:03 UTC, andreslcm commented on src/components/Usuario.vue
> +      this.usuario.nombre = this.getDatosUsuario.nombre;
En este caso, al tratarse de un getter, no se ponen los () porque devuelve el estado (propiedad) y le aplica una función (sin modificarlo).  Todavía no tengo los conocimientos lo suficientemente sólidos para explicar la diferencia con los términos apropiados. Sí sé que para llamar a las acciones del store sí es necesario colocar los (). De hecho, si se le quiere pasar un parámetro a un getter, hay que ponerlo a retornar una función que sí acepte parámetros.

2019-11-07 17:05 UTC, andreslcm commented on src/store.js
> +        });
Lanza un error por consola con el código pertinente. Sin embargo, sí hay que agregarles el catch a todos estos métodos para que muestren el httpstatus que envía la API.

2019-11-07 17:06 UTC, andreslcm commented on src/components/Clientes.vue
> +.iconos:hover {
Entendido.

2019-11-07 17:06 UTC, andreslcm commented on src/components/Clientes.vue
> +.contenedor-tabla {
Entendido.

2019-11-07 17:07 UTC, andreslcm commented on src/components/Estadisticas.vue
> +</style>
Sí, señor. Otra persona está trabajando en él. En las próximas horas debería subir el contenido.

2019-11-07 17:13 UTC, andreslcm commented on src/store.js
> +        });
En cuanto a la extensión del PR, tienes razón. No hice PR más pequeños por esperar a ver si daba chance de hacer los tests y enviarlo todo junto (según vuestras exigencias); no obstante, tampoco podía parar el desarrollo a la espera de estos tests, no habríamos pasado del login.

2019-11-07 21:23 UTC, didierrenardub commented on src/store.js
> +        });
Claro, pero habría que mostrar algún feedback en la página de que algo falló...

2019-11-07 22:16 UTC, andreslcm commented on src/store.js
> +        });
Sí, señor. Esto lo tenemos pendiente. Mañana pongo esos catch.

2020-02-07 23:49 UTC, didierrenardub commented on src/components/Registro.vue
> +        var comparacion = true;
Esta variable tiene que estar declarada fuera del if, de lo contrario no va a existir más al salir del mismo.

2020-02-07 23:49 UTC, didierrenardub commented on src/components/Registro.vue
> +        var longitud = true;
Pasa lo mismo con esta variable, tiene que estar definida en un scope superior

2020-02-07 23:50 UTC, didierrenardub commented on src/components/Registro.vue
> +        document.getElementById("submit").style.display = "none";
Tanto `"block"` como `"none"` se repiten bastante; hay que definir constantes y usarlas en su lugar

2020-02-07 23:51 UTC, didierrenardub requested changes
Muy bien; deberías arreglar los dos comentarios nuevos más los existentes para que resulte aprobado el PR!

2020-02-10 20:38 UTC, franciscoMigliardi24 commented on src/components/Registro.vue
> +        document.getElementById("submit").style.display = "none";
ahora mismo me pongo a corregir estos problemas!

2020-02-11 03:04 UTC, didierrenardub commented on src/components/Registro.vue
> +      var comparacion;
Hay que inicializar todas las variables con algún valor para que no haya peligro de que se acceda a un valor indefinido al usarse.

2020-02-12 20:03 UTC, didierrenardub approved these changes
Felicitaciones, se puede mergear este PR!

2020-02-12 20:04 UTC, merged